export default function ComparisonSection() {
  const comparisons = [
    {
      title: "Hyper-Speed",
      description: "Crawl millions of pages in minutes, not days. Built for enterprise scale.",
      color: "primary",
    },
    {
      title: "AI-Driven",
      description: "Actual code implementations generated by context-aware AI engines.",
      color: "secondary",
    },
    {
      title: "Dev-Friendly",
      description: "Robust API and Git integrations for seamless CI/CD SEO workflows.",
      color: "tertiary",
    },
    {
      title: "Real-Time",
      description: "Zero lag between discovery and reporting. Know the moment rankings shift.",
      color: "surface-tint",
    },
  ]

  return (
    <section className="py-24 px-8 max-w-7xl mx-auto">
      <h2 className="text-3xl md:text-4xl font-black text-center mb-16 tracking-tight text-white">
        How Odito Stands Out
      </h2>
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        {comparisons.map((item, index) => (
          <div
            key={index}
            className={`glass-card p-8 rounded-2xl border-l-4 border-${item.color}`}
          >
            <h3 className="text-xl font-bold mb-4 text-white">{item.title}</h3>
            <p className="text-sm text-on-surface-variant">{item.description}</p>
          </div>
        ))}
      </div>
    </section>
  )
}
